- name: Copy Source Code
  hosts: SWARM

#  serial: 3
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_pass: 123
    stage: 1
  tasks:
    - include_tasks: prepare.yml
      when: stage == 0

    - include_tasks: run.yml
      when: stage == 1

    - include_tasks: finish.yml
      when: stage == 2
