- name: Copy Source Code
  hosts: SWARM
  vars:
    stage: 2
  tasks:
    - include_tasks: prepare.yml
      when: stage == 0

    - include_tasks: run.yml
      when: stage == 1

    - include_tasks: finish.yml
      when: stage == 2
