"api_base": {
  "GPT": "https://xxx.com/v1",
}
"api_key": {
  "GPT": "xxx",

    "VLM": "xxx",

  "QWEN": "xxx",
  "CLAUDE": "input your claude api here"
}
"model": {
  "VLM": "gpt-4o",
  "GPT": "o1-mini",
  #  "GPT": "o1-preview",
  "QWEN": "qwen-vl-plus",
  "CLAUDE": "input the claude model here"
}
