"api_base": {
  "GPT": "https://api.openai.com",
  # any model provider can be added here，if model provider supports openai api format,
  #  you can use the same api_base and api_key to access the model.
  #  "GPT": "https://api.deepseek.com",
  "VLM": "https://api.openai.com",
  "QWEN": "https://dashscope.aliyuncs.com/compatible-mode/v1",
}
"api_key": {
  "GPT": "sk-xxxx",
  "VLM": "sk-xxx",
  "QWEN": "sk-xxx",
  "CLAUDE": "input your claude api here"
}
"model": {
  "VLM": "",
#    "GPT": "gpt-4o-2024-11-20",
  "GPT": "DMXAPI-HuoShan-DeepSeek-V3",
  "QWEN": "qwen-vl-plus",
  "CLAUDE": "input the claude model here"
}