name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: docker-compose -f ci/docker-compose.yml up python_build
