name: Run Unit Tests with Docker

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - 'feature-*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: huabench/code-llm
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run unit tests in Docker container
      env:
          API_KEY: ${{ secrets.LLM_API_KEY }}
      run: docker run -v .:/src -e API_KEY=$API_KEY huabench/code-llm /bin/bash -c "conda run --no-capture-output -n py310 python -m unittest discover -v"
