name: Run Unit Tests with Docker

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: huabench/code-llm
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Docker image
      uses: actions/cache@v2
      with:
        path: /path/to/docker/image.tar
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-
      
    - name: Load Docker image from cache
      if: steps.cache-docker.outputs.cache-hit == 'true'
      run: docker load -i /path/to/docker/image.tar
      
    - name: Run unit tests in Docker container
      env:
        API_KEY: ${{ secrets.LLM_API_KEY }}
        API_BASE: ${{ secrets.LLM_API_BASE }}
      run: |
        docker run -v .:/src -e API_KEY=$API_KEY API_BASE=$API_BASE huabench/code-llm /bin/bash -c "\
        roscore & \
        sleep 5; \
        conda run --no-capture-output -n py310 coverage run -m unittest discover -v"
